# Generated by Django 3.2.8 on 2021-10-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=200)),
                ('organization_link', models.CharField(max_length=500)),
                ('donation_request_message', models.TextField()),
            ],
        ),
    ]
