# Generated by Django 3.2.8 on 2021-10-20 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_request_message',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization_link',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='platform_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 20, 8, 51, 8, 82131, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
